### ISSUE TITLE
"Can not start Opera" (Windows)

### ISSUE THREAD

**Issue by tienthanh8490** [karma-runner/karma-opera-launcher#10]
I am testing on Opera 28 (Windows). Opera was actually opened (I modified  , but the test never seems to be loaded, and Karma keeps throwing error "Can not start Opera" and skips all the tests.

Tried all options in #3 but still does not work.

The issue seems to be on this._getOptions since this works for some people. @vojtajina could you please advise on which option can be used ? Or where can I find information about this matter so that I can fix it myself and pull request ? Thanks.

**Comment by inf3rno** [comment]
+1 The same here. It does not wait enough before retry. Maybe the timeout is broken, I am not sure, not familiar with the code.

**Comment by bennyn** [comment]
Tested it today on **Windows 10 Pro** (Insider Preview Build 10565) with **Opera 32.0** and it failed.

Output was the following:

```
24 10 2015 23:21:56.936:INFO [karma]: Karma v0.13.12 server started at http://localhost:9876/
24 10 2015 23:21:56.946:INFO [launcher]: Starting browser Opera
24 10 2015 23:21:57.009:ERROR [launcher]: Cannot start Opera

24 10 2015 23:21:57.012:INFO [launcher]: Trying to start Opera again (1/2).
24 10 2015 23:21:57.068:ERROR [launcher]: Cannot start Opera

24 10 2015 23:21:57.070:INFO [launcher]: Trying to start Opera again (2/2).
24 10 2015 23:21:57.134:ERROR [launcher]: Cannot start Opera

24 10 2015 23:21:58.708:INFO [Opera 32.0.1948 (Windows 10 0.0.0)]: Connected on socket Q5S2dgyLAR1gt1g9AAAB with id 55564777
Opera 32.0.1948 (Windows 10 0.0.0): Executed 10 of 10 SUCCESS (0.092 secs / 0.041 secs)
24 10 2015 23:22:00.297:ERROR [launcher]: Opera failed 2 times (cannot start). Giving up.

Done, without errors.
```

It started Opera 4x and I could see a Karma page in Opera (with status "disconnected"). So the problem might be that Opera does not report to the Karma runner that it has been successfully started.

**Comment by inf3rno** [comment]
I tested with opera32 with win7 x64.

**Comment by egoroof** [comment]
I've got the same error :(

**Comment by valkirilov** [comment]
+1

**Comment by dicbrus** [comment]
the same error, 'cannot start Opera'
Windows 10

**Comment by JeanPerriault** [comment]
Same kind of error, it launches four opera instances each time

```
23 05 2016 13:42:28.908:WARN [karma]: No captured browser, open http://localhost:9876/
23 05 2016 13:42:28.924:INFO [karma]: Karma v0.13.22 server started at http://localhost:9876/
23 05 2016 13:42:28.932:INFO [launcher]: Starting browser Opera
23 05 2016 13:42:29.070:ERROR [launcher]: Cannot start Opera

23 05 2016 13:42:29.111:INFO [launcher]: Trying to start Opera again (1/2).
23 05 2016 13:42:29.113:WARN [temp-dir]: Failed to create a temp dir at C:\Users\XXXXX\AppData\Local\Temp\karma-93465476
23 05 2016 13:42:29.727:ERROR [launcher]: Cannot start Opera
```

Sometimes at this step it is able to launch my test suite one time (but I'm NOT in single run mode)
Then I've got other errors

```
23 05 2016 13:42:33.469:INFO [launcher]: Trying to start Opera again (2/2).
23 05 2016 13:42:33.470:WARN [temp-dir]: Failed to create a temp dir at C:\Users\XXXXX\AppData\Local\Temp\karma-93465476
23 05 2016 13:42:35.157:ERROR [launcher]: Cannot start Opera

23 05 2016 13:42:38.185:ERROR [launcher]: Opera failed 2 times (cannot start). Giving up.
Opera 37.0.2178 (Windows 7 0.0.0): Executed 86 of 89 (1 FAILED) (skipped 3) DISCONNECTED (16.564 secs / 0.951 secs)
Fatal error: Cannot read property '93465476' of null
```

Using `node 6.1.0`, `npm 3.8.9`, `karma 0.13.22`, `karma-opera-launcher 1.0.0` (and also using `karma-coverage 1.0.0` among others karma and jasmine related modules)

**Comment by ghost** [comment]
Still not fixed. :S

**Comment by irvinzz** [comment]
I have same issue and i found problem. Opera spawning another instance of itself. To tell it not to do that, you need specify "--ran-launcher".
So i made PR: https://github.com/karma-runner/karma-opera-launcher/pull/17
Fixed module Repo: https://github.com/irvinzz/karma-opera-launcher

**Comment by begin-again** [comment]
Same issue: 
WIndows 10 
Opera v44

**Comment by mmzhong** [comment]
Inspired by @irvinzz , it works for me :
```js
browsers: ['OperaCustom'],
customLaunchers: {
  OperaCustom: {
    base: 'Opera',
    flags: ['--ran-launcher']
  }
}
```
window 10 x64, Opera v48.0

**Comment by ghost** [comment]
@mmzhong Thanks! That solved here too.

**Comment by WallyB84** [comment]
I'm running window 10 x64, Opera v57.0.3098.102
I'm still having essentially the same problem. The noted "--ran-launcher" work-around does seem to enable the unit tests to run in one instance of Opera while there are two others that also open. Its not ideal.

**Comment by Ratstail91** [comment]
+1, two extra windows still open.

**Comment by vbrin27** [comment]
Windows 10
Opera 70
```browsers: ['OperaCustom'],
customLaunchers: {
    OperaCustom :{
        base: 'Opera',
        flags: ['--start-maximized','--ran-launcher']
    }
}
```
But I still face "cannot start opera" issue.

**Comment by nnfighting** [comment]
I still face "cannot start opera" issue.
